### ISSUE TITLE
ANR issue

### ISSUE THREAD

**Issue by SamirAhmedSaad** [Kaaveh/sdp-compose#5]
Recently, I encountered an **ANR** issue reported on Crashlytics. The stack trace points to the following method

**ir.kaaveh.sdpcompose.SdpHelperKt.getFieldId (SdpHelper.kt:41)**

main (native): tid=1 systid=31385
00 pc 0x99ccc libc.so (syscall + 28) (BuildId: e48f6233c3b033321b203dd90143e00e)
01 pc 0x22a220 libart.so (art::ConditionVariable::WaitHoldingLocks + 136) (BuildId: c35c9ebf7bb06435e4b31977d87bd5d5)
02 pc 0x9909e8 libart.so (artJniMethodEnd + 344) (BuildId: c35c9ebf7bb06435e4b31977d87bd5d5)
03 pc 0x78573c libart.so (art_jni_method_end + 12) (BuildId: c35c9ebf7bb06435e4b31977d87bd5d5)
       at android.content.res.AssetManager.nativeGetResourceIdentifier(Native method)
       at android.content.res.AssetManager.getResourceIdentifier(AssetManager.java:833)
       at android.content.res.ResourcesImpl.getIdentifier(ResourcesImpl.java:304)
       at android.content.res.Resources.getIdentifier(Resources.java:2328)
       at ir.kaaveh.sdpcompose.SdpHelperKt.getFieldId(SdpHelper.kt:41)
       at ir.kaaveh.sdpcompose.SdpHelperKt.sdpGet(SdpHelper.kt:33)
       at ir.kaaveh.sdpcompose.SdpHelperKt.getSdp(SdpHelper.kt:14)

**Comment by Kaaveh** [comment]
Thanks for your report! Would you like to work on this issue?

**Comment by Kaaveh** [comment]
Thanks for the report and apologies for the delay in fixing it.
I will release a new version today to fix it.
Enjoy using it.🙌
